name: 07 - Using Expressions
on:
 push:
 workflow_dispatch:
  inputs:
   debug:
    type: boolean
    default: false
jobs:
  echo-to-the-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: '[debug]'
        if: ${{inputs.debug}}
        run: |
         echo " Triggered by:${{github.event_name}} "
         echo "Branch: ${{github.ref}}"
         echo "Commit SHA: ${{github.sha}}"
         echo "Runner OS: ${{runner.os}}"
      - name: Expressions
        if: ${{inputs.debug && github.ref=='refs/heads/master'}}
        run: |
         echo "I was triggered from master".
      - name: Greeting
        run: echo "Hello world"
        

  
